version: '2'

services:
    nginx:
        build: ./images/nginx
        container_name: nginx
        restart: always
        network_mode: host
        depends_on:
            - php7
        volumes:
            - ./conf/vhost:/etc/nginx/conf.d
            - ./volumes/logs/nginx:/var/log/nginx
            - /app/data:/srv
        env_file: .env
    php7:
        image: dockette/php:7.1-fpm
        container_name: php7
        restart: always
        network_mode: host
        ports:
            - 9000:9000
        volumes:
            - /app/data:/srv
            - ./volumes/logs/php:/var/log
        working_dir: /srv
        env_file: .env

    mysql:
        build: images/mysql
        ports:
            - 3306:3306
        volumes:
            - ./volumes/data/mysql:/var/lib/mysql
        env_file: .env

    ssdb:
        build: images/ssdb
        volumes:
            - ./volumes/data/ssdb:/data
        ports:
            - "16379:16379"

    redis:
        build: images/redis
        ports:
            - 6379:6379